export { default as Dashboard } from "./Dashboard.page";
export { default as AdminPlayers } from "./AdminPlayers.page";
export { default as AdminPlayer } from "./AdminPlayer.page";
export { default as AdminDecks } from "./AdminDecks.page";
export { default as AdminDeck } from "./AdminDeck.page";
export { default as AdminTournaments } from "./AdminTournaments.page";
export { default as AdminTournament } from "./AdminTournament.page";
export { default as AdminEquipments } from "./AdminEquipments.page";
export { default as AdminEquipment } from "./AdminEquipment.page";
